### ISSUE TITLE
Visualizer: AUTOMATIC1111 improvements

### ISSUE THREAD

**Issue by vegu-ai-tools** [vegu-ai/talemate#142]
Look what options make sense to expose the the UX without overloading the agent config options, there are probably some vital / often used ones that are currently missing.

**Comment by vegu-ai-tools** [comment]
if A1111 users can list some the most vital things to expose here  that'd be helpful - with the caveat that i want to avoid overloading the agent config UX in talemate with options, so id prefer to be picky what to add.

**Comment by MiyeonLin** [comment]
The best would be to change sampler settings and cfg for now. For comfy we can just create a custom workflow to do that and import.
