### ISSUE TITLE
Question: Is it possible to reset or delete scenes from UI? 

### ISSUE THREAD

**Issue by valden80** [vegu-ai/talemate#150]
Maybe I'm blind, but I can't find those basic functions...

Right now, if I want to reset scene to starting point - I need to export it (with option "reset progress"), then import back from file. Somewhat working as reset... But I can't find any way to delete old scene if I not needed it anymore from UI. 
(Well, I can go to the file system and manually delete .json file, but I'm not sure that it's not break something other...)

Also, I can't find a way to import/export entries from the "world" tab in world editor. I think it's not possible right now too?

**Comment by vegu-ai-tools** [comment]
No UX function to delete or manage scenes currently, it is safe to just go into the scenes directory and delete the file.

> Also, I can't find a way to import/export entries from the "world" tab in world editor. 

There is no import / export of individual pieces of the scene.

There is an undocumented `!reset` command you use to reset the scene, but i haven't tested it in a while and i am not sure it gets everything. - just type it in the chat input when the scene is open.

I've opened #151 and #152 to track some of these issues. 

I can see the use of being able import / export individual pieces as well, but don't want to spec this out currently, if its important to you please go ahead and open a separate issue for it.
