### ISSUE TITLE
Bug still present in current 0.27 even though marked as fixed. ("rubberband" in editors)

### ISSUE THREAD

**Issue by valden80** [vegu-ai/talemate#153]
I talking about this bug: https://github.com/vegu-ai/talemate/issues/138

Even if it's marked as fixed for current 0.27, I still experience exactly this behavior in the editors of world and characters.

Tested in chromium and Vivaldi browsers (I'm on Manjaro Linux system).
Installed talemate from git (main branch clone), not a docker, manual install.

Maybe it's will work better, if processing actions for text will be tied to events like "on focus lost" of these text areas? Right now it's seems to triggering from timeout of typing...
(Sorry, I'm not JS programmer, maybe it's not possible at all for it...)

**Comment by vegu-ai-tools** [comment]
Previous fix was to increase the timeout, if this is still happening for people i agree maybe the approach needs to be changed, will look at it again, thanks.

**Comment by valden80** [comment]
No more problems with this in 0.28, thanks.
