### ISSUE TITLE
Bug: The "Tab" key don't select more then one NPC in the group chat.

### ISSUE THREAD

**Issue by valden80** [vegu-ai/talemate#158]
More or less self explaining. 

Example: I have three characters in chat:

Ben (Player)
Anna (NPC)
Bobby (NPC)

With pressing Tab I can switch between - Ben, Anna, Narrator. But not Bobby, even when I ensuring - he is active and may respond by himself.

Tested in 0.28 branch.

**Comment by vegu-ai-tools** [comment]
Bug confirmed, thanks for the feedback.

**Comment by valden80** [comment]
Working now, thanks.
