### ISSUE TITLE
KoboldCpp support

### ISSUE THREAD

**Issue by vegu-ai** [vegu-ai/talemate#16]
This needs more looking at, whether or not this can suitably made to work with talemate.

Main issue is that different agents in talemate use different inference parameters and from playing around with it a bit it seems like koboldcpp maintains a config state of parameters instead of allowing to specify parameters per request to their api.

This makes it sorta awkward (would need to send re-configure requests before each request)

**Comment by vegu-ai-tools** [comment]
This should be fixed through the OpenAI API Compatible client added in 0.18.0
