### ISSUE TITLE
In 0.28 branch, current commit, default "simulation suite" is broken.

### ISSUE THREAD

**Issue by valden80** [vegu-ai/talemate#161]
On any input it responding with error:
``Unhandled Error: Scene.context_history() takes from 1 to 2 positional arguments but 3 were given``

Maybe it's outdated and shouldn't work with changes in 0.28, but at least some notification about it will be good.

**Comment by vegu-ai-tools** [comment]
Not intentional - will take a look, thanks.

**Comment by vegu-ai-tools** [comment]
Should be fixed.

**Comment by valden80** [comment]
Fixed, thanks.
