### ISSUE TITLE
More Control Over AI Agent Responses

### ISSUE THREAD

**Issue by maxthraxx** [vegu-ai/talemate#47]
Just dropping another suggestion here (hi, yes, it is me again!). While I love Talemate's autonomous random functions that decide when the narrator should narrate and when characters should respond and in what order, I'd love to have the ability to turn that off and be able to choose what AI agent responds and when.

So, as an example in gameplay: I would type in a response as my character and hit enter, and Talemate would enter that into context. But, in this optional manual mode, Talemate will not automatically respond to my entry. Instead I would have to hit one of three buttons (this is just my idea on it!): narrate, actor response (this button will select the most appropriate actor at the Conversation agent's direction), or specific actor response (here I should be able to input the name of the actor I want to have respond to the current context.)

The primary reason for this, personally, is that I am often getting a chain of multiple AI responses, like narration -> character response -> different character response, etc. or the other way around. While that's great, I am using OpenAI (I can't run a local LLM) and the token costs add up quite quickly with all the AI responses, some of which I don't actually need (maybe I just want the narrator to narrate, or one character to respond and that's it.)

Thanks for reading and considering, and I hope youve had a nice holiday period :)

**Comment by vegu-ai-tools** [comment]
A manual response type selection mode makes sense to me - for the reason you stated, and additionally:

i use mostly local llms, and while token usage isn't an issue there i am noticing a lot that with stuff like auto narration it happens at times where i dont really want it or it tends to get carried away (local llm not adhering to the restrictions of the prompt) and i end up removing it.

so i think this could look like this:

- a manual mode checkbox that toggles between the current automatic mode and the new manual mode
- if manual mode is active the hotkeys at the bottom are used for AI side progression of the story 
- hotkeys to be added: 
  - sensory narration (the current auto narration that can happen after dialogue)
  - dialogue (conversation agent selects actor and generates dialogue)
  - specific character dialogue (user selects from a list of characters)
  - auto continue (AI selects next course of action, sorta what would happen automaticall in auto mode)
