### ISSUE TITLE
First pass at actor management

### ISSUE THREAD

**Issue by vegu-ai-tools** [vegu-ai/talemate#57]
Add character / actor management tools to the hotbar

- Introduce character: Becomes available when there is a character picked up by the world state that is currently not an active participant. Introduce the character to make them join the conversation.
- Scene exit: character: Active characters can now be called to exit the scene (with narration to go along with it), removing them from the conversation and the scene, they will not be deleted from the game and can be recalled later.
- Scene entry: character: Inactive characters can be called back into the scene (with narration to go along with it).

**Comment by maxthraxx** [comment]
Great ideas here. Am not sure if you've already thought of this, but could you make the narration of scene exit and entry optional and just either add them to the scene or remove them without triggering narration?

Reason for this being is often I would be creating a new scene, and would like to quickly add and remove the "cast of characters" for that scene. This would probably be in Creative Mode I'd imagine.

Thanks again for all your fantastic work!

**Comment by vegu-ai-tools** [comment]
Yeah makes sense - still playing with it at the moment but the way it works right now is:

Example for adding a character:

- check through AI if the character is currently active in the scene, and if not prompt the player how they want the character to enter the scene. 
  - if AI determines character is currently not active in the scene
    - if the player enters a prompt (e.g., John comes in through the window in a hurry) narration will be generated based on that
    - if the player does not enter a prompt, the AI generates something based on context alone
  - if AI determines character is already in the scene, no narration will be generated to introduce them
  
 Now, jury is out how accurately these active / not active determinations will be, but i fathom GPT-3.5+ will be solid. The open source models i tested so far (7b to 8x7b) seem to have no issues with it either.
 
That being said, i will add a modified version for each that never prompts / generates narration [probably hold down ctrl or something]
