### ISSUE TITLE
Add GPT-4 Turbo updated model

### ISSUE THREAD

**Issue by maxthraxx** [vegu-ai/talemate#62]
OpenAI just released an updated version of GPT-4 Turbo called `gpt-4-0125-preview` which should be added to the available models. I think the old GPT-4 Turbo, `gpt-4-1106-preview` is still available however.

Maybe add (1106) and (0125) as differentiators for these two.

I would do this myself (looks like just an easy fix in the Vue file) but not super familiar with github functions and such.

**Comment by vegu-ai-tools** [comment]
@maxthraxx added those before i release 0.18.0 just now
