### ISSUE TITLE
OpenAI GPT-4-Turbo model name error

### ISSUE THREAD

**Issue by maxthraxx** [vegu-ai/talemate#68]
Should be `gpt-4-0125-preview` not `gpt-4-turbo-preview`.

**Comment by vegu-ai-tools** [comment]
From the announcement

> For those who want to be automatically upgraded to new GPT-4 Turbo preview versions, we are also introducing a new gpt-4-turbo-preview model name alias, which will always point to our latest GPT-4 Turbo preview model. 

So that should be pointing to the 0125 version right now, and looks working to me - are you seeing errors?

**Comment by vegu-ai-tools** [comment]
Although now i am pondering if there is a case to be made to keep explicit versioning of their API as choices as well.  🤷

**Comment by maxthraxx** [comment]
Aha ok, I missed that change, good catch!

Yeah, potentially a version selection could be good, but then that would require a bit of extra maintenance to maintain the list of OpenAI model versions. Alternatively, you could create an input box for people to specify their own model version via a text string, then it would be on them to use the correct version string.

**Comment by vegu-ai-tools** [comment]
decided to add 0125 explicitly as well
