### ISSUE TITLE
Issues with OpenAI Compatible API

### ISSUE THREAD

**Issue by lunarkoi** [vegu-ai/talemate#78]
Hey, thank you for the great work!

I'm just here to report on a bug.

openai_compat.py:line 68 - causes issues with mistral.ai and deepinfra.com API
* mistral.ai - only allows 'open-mistral-7b' model to be chosen and will override any other model name manually specified
* deepinfra.com - does not allow it to run at all

The temporary solution I found:
* Raising an error on line 68, the catch is, it will quickly fill the logs with "get_model_name error"

```
66   async def get_model_name(self):
67        try:
68            raise TypeError("foo") # model_name = await super().get_model_name()
```

With the above fix, I'm able to enter the 'API URL' and 'Manually specify model name' and it seems to be working.

PS: 
In addition, I also removed line 47 and 48 on my local copy for the "/v1"

Here are the API and models I'm using:

"https://api.deepinfra.com/v1/openai", "cognitivecomputations/dolphin-2.6-mixtral-8x7b"
"https://api.mistral.ai/v1", "mistral-medium"

**Comment by vegu-ai-tools** [comment]
@lunarkoi thanks for the detailed report and possible workarounds - will have a look

**Comment by vegu-ai-tools** [comment]
Mistal AI will get its own client
OpenAI compat client will be fixed for greater compatibility by leaving api url and model name specification entirely up to the user config.

Once 0.21.0 is release the following setting should work for DeepInfra:

![image](https://github.com/vegu-ai/talemate/assets/152010387/1d034d97-954a-4934-a2bb-d0e38fe20e7f)
