### ISSUE TITLE
how to disable network url?

### ISSUE THREAD

**Issue by FemBoxbrawl** [vegu-ai/talemate#92]
I only want it running locally. how do i disable the network URL

**Comment by vegu-ai-tools** [comment]
edit the file you use to start it and change `0.0.0.0` to `localhost` or `127.0.0.1` for the backend

then also add it to the front end by changing to `npm run serve -- --host 127.0.0.1 --port 8080`

**Comment by vegu-ai-tools** [comment]
will add a -local version of the startup script in 0.23.0
