### ISSUE TITLE
User Friendliness/ Documentation

### ISSUE THREAD

**Issue by Dripstylish** [vegu-ai/talemate#98]
First of all, what an amazing project! I'm blown away!

Though, while the UI itself is pleasant to look at and use, I do feel that there's a lack of user guidance.

It would be nice to see a more in-depth documentation on how to use the frontend, including the game mode, creative mode, world state manager, the agents...
Some buttons and areas have descriptions and tooltips. Some don't, and require a bit more time to understand. It would be nice with a bit more consistency and some time dedicated to writing up a solid User Guide showcasing all of it's features and possibilities.

**Comment by vegu-ai-tools** [comment]
Hi @Dripstylish, thanks for the feedback.

I agree, i've been hesitant to dive "too deep" into documentation, simply because of how much i've been changing stuff around (drastically in some cases), but i feel a lot of the components that are there now that are stable enough that spending time on documentation makes sense.

What are the areas which have been the most unclear to you?

**Comment by Dripstylish** [comment]
1. The game mode and world state manager.
2. The creative mode and how to create your own scenarios.
3. Agent customization and potentially extending with custom agents - as well as the agent prompt template overwrites.
I think the above is what most users would be interested in.

I'm aware that you have a few documentation files, for example about the templates. And I was able to learn a lot just from skimming the code base and watching the backend logs - but I don't think the average user would be able to do that.

If nothing else, then I think a "getting started" guide, that helps you through the more stable "game"-loop, would help make it a lot less daunting for a new user.

Since you're working in milestone releases, you could always keep two branches. One that's the current stable version, which has a documentation for it's features. And one that's still unstable and undocumented, which you move to stable only after updating the documentation.
