### ISSUE TITLE
Template management within the World State Manager

### ISSUE THREAD

**Issue by Dripstylish** [vegu-ai/talemate#99]
Feature request: The ability to create separate templates for all aspects of a scene/scenario - from the frontend - neatly within the scene manager/world state manager.

How I imagine it would function:
At the top of a category that allows you to add multiple entries or elements - allow for importing or saving templates that only applies to said category.
It would also be nice to both have global and local templates; with global templates being available in all scenes, and local only applying to new (characters, states, world entries..) within the same scene.

Usage example:
For example, allowing the creation of templates to quickly add attributes to a character, that can then be filled in/generated as normal. This would make it easier to create characters that have the same attributes, especially when you have certain attributes you often repeat on multiple characters, or across multiple scenes.

If this feature already exists, then make it less obscure by serving it directly where it's used.

**Comment by vegu-ai-tools** [comment]
That makes sense to me. There will be a push for better / additional creative tooling soon, ill keep this in mind, thanks.
